apiVersion: v1
kind: Service
metadata:
 name: code-server
 namespace: code-server
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: code-server
      containers:
      - image: 10.109.120.111:5000/code-server:4.8.3
        imagePullPolicy: Always
        name: code-server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PASSWORD
          value: "1234"
        volumeMounts:
        - name: home
          mountPath: /root/gdrive
