apiVersion: v1
kind: PersistentVolume
metadata:
  name: gdrive
  labels:
    type: local
    app: code-server
spec:
  storageClassName: openebs-hostpath
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/openebs/local/gdrive"