{{- if .Values.compiler.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "polyaxon.fullname" . }}-compiler
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-compiler
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreWorker" . | indent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "polyaxon.fullname" . }}-compiler
  minReplicas: {{ .Values.compiler.hpa.minpods }}
  maxReplicas: {{ .Values.compiler.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.compiler.hpa.cputhreshold }}
{{- end }}
