apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-platform-config
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-platform-config
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
data:
  # Cluster
  {{- if .Values.allowedHosts }}
  POLYAXON_ALLOWED_HOSTS: {{ toJson .Values.allowedHosts | quote }}
  {{- end }}
  # Admin
  POLYAXON_ADMIN_NAME: {{ .Values.user.username | quote }}
  POLYAXON_ADMIN_MAIL: {{ .Values.user.email | quote }}
  POLYAXON_PASSWORD_LENGTH: {{ default "6" .Values.passwordLength | quote }}
  # Email
  {{- if .Values.email.enabled }}
  {{- if .Values.email.from }}
  POLYAXON_EMAIL_FROM: {{ .Values.email.from | quote }}
  {{- end }}
  {{- if .Values.email.subjectPrefix }}
  POLYAXON_EMAIL_SUBJECT_PREFIX: {{ .Values.email.subjectPrefix | quote }}
  {{- end }}
  POLYAXON_EMAIL_HOST: {{ .Values.email.host | quote }}
  POLYAXON_EMAIL_PORT: {{ .Values.email.port | quote }}
  POLYAXON_EMAIL_USE_TLS: {{ .Values.email.useTls | quote }}
  {{- if .Values.email.hostUser }}
  POLYAXON_EMAIL_HOST_USER: {{ .Values.email.hostUser | quote }}
  {{- end }}
  {{- if .Values.email.backend }}
  POLYAXON_EMAIL_BACKEND: {{ .Values.email.backend | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.scheduler.enabled }}
  POLYAXON_SCHEDULER_ENABLED: {{ .Values.scheduler.enabled | quote }}
  {{- if eq .Values.broker "redis" }}
  POLYAXON_BROKER_BACKEND: {{ .Values.broker }}
  POLYAXON_REDIS_CELERY_BROKER_URL: {{ template "redis.host" . }}:{{ template "redis.port" . }}/0
  POLYAXON_REDIS_CELERY_RESULT_BACKEND_URL: {{ template "redis.host" . }}:{{ template "redis.port" . }}/1
  POLYAXON_REDIS_SESSIONS_URL: {{ template "redis.host" . }}:{{ template "redis.port" . }}/2
  POLYAXON_REDIS_HEARTBEAT_URL: {{ template "redis.host" . }}:{{ template "redis.port" . }}/3
  POLYAXON_REDIS_HOST: "{{ template "redis.host" . }}"
  POLYAXON_REDIS_PORT: "{{ template "redis.port" . }}"
  {{- else }}
  POLYAXON_AMQP_URL: "{{ template "rabbitmq.host" . }}:{{ template "rabbitmq.port" . }}"
  POLYAXON_RABBITMQ_USER: "{{ template "rabbitmq.user" . }}"
  {{- end }}
  # Queues
  POLYAXON_INTERVALS_RUNS_SCHEDULER: {{ .Values.intervals.runsScheduler | quote }}
  POLYAXON_INTERVALS_OPERATIONS_DEFAULT_RETRY_DELAY: {{ .Values.intervals.operationsDefaultRetryDelay | quote }}
  POLYAXON_INTERVALS_OPERATIONS_MAX_RETRY_DELAY: {{ .Values.intervals.operationsMaxRetryDelay | quote }}
  {{- end }}
  POLYAXON_INTERVALS_COMPATIBILITY_CHECK: {{ .Values.intervals.compatibilityCheck | quote }}
  # DB
  POLYAXON_DB_USER: {{ template "pgsql.user" . }}
  POLYAXON_DB_NAME: {{ template "pgsql.database" . }}
  POLYAXON_DB_PORT: "{{ template "pgsql.port" . }}"
  POLYAXON_DB_CONN_MAX_AGE: "{{ template "pgsql.connMaxAge" . }}"
  POLYAXON_DB_HOST: "{{ template "pgsql.host" . }}"
  {{- if .Values.externalServices.postgresql.options }}
  POLYAXON_DB_OPTIONS: {{ toJson .Values.externalServices.postgresql.options | quote }}
  {{- end }}
  {{- if .Values.externalServices.analytics.enabled }}
  POLYAXON_ANALYTICS_BACKEND: {{ default "default" .Values.externalServices.analytics.backend | quote }}
  {{- end }}
  {{- if .Values.externalServices.transactions.enabled }}
  POLYAXON_TRANSACTIONS_BACKEND: {{ default "default" .Values.externalServices.transactions.backend | quote }}
  {{- end }}
  {{- if .Values.metrics.enabled }}
  POLYAXON_METRICS_BACKEND: "statsd"
  POLYAXON_METRICS_OPTIONS: {{ include "config.metrics.options" . | fromJson | toJson | quote }}
  {{- else if .Values.externalServices.metrics.enabled }}
  POLYAXON_METRICS_BACKEND: {{ default "default" .Values.externalServices.metrics.backend | quote }}
  {{- end }}
  {{- if .Values.externalServices.errors.enabled }}
  POLYAXON_ERRORS_BACKEND: {{ default "default" .Values.externalServices.errors.backend | quote }}
  {{- end }}
  {{- if .Values.externalServices.allowedVersions }}
  POLYAXON_ALLOWED_VERSIONS: {{ toJson .Values.externalServices.allowedVersions | quote }}
  {{- end }}
  # Auth
  {{- if .Values.ldap.enabled }}
  POLYAXON_AUTH_LDAP: "true"
  POLYAXON_AUTH_LDAP_SERVER_URI: {{ .Values.ldap.serverUri | quote }}
  POLYAXON_AUTH_LDAP_GLOBAL_OPTIONS: {{ toJson .Values.ldap.globalOptions | quote }}
  POLYAXON_AUTH_LDAP_CONNECTION_OPTIONS: {{ toJson .Values.ldap.connectionOptions | quote }}
  POLYAXON_AUTH_LDAP_BIND_DN: {{ .Values.ldap.bindDN | quote }}
  POLYAXON_AUTH_LDAP_USER_SEARCH_BASE_DN: {{ .Values.ldap.userSearchBaseDN | quote }}
  POLYAXON_AUTH_LDAP_USER_SEARCH_FILTERSTR: {{ .Values.ldap.userSearchFilterStr | quote }}
  POLYAXON_AUTH_LDAP_USER_DN_TEMPLATE: {{ .Values.ldap.userDNTemplate | quote }}
  POLYAXON_AUTH_LDAP_START_TLS: {{ .Values.ldap.startTLS | quote }}
  POLYAXON_AUTH_LDAP_USER_ATTR_MAP: {{ toJson .Values.ldap.userAttrMap | quote }}
  POLYAXON_AUTH_LDAP_GROUP_SEARCH_BASE_DN: {{ .Values.ldap.groupSearchBaseDN | quote }}
  POLYAXON_AUTH_LDAP_GROUP_SEARCH_GROUP_TYPE: {{ .Values.ldap.groupSearchGroupType | quote }}
  {{- if .Values.ldap.requireGroup }}
  POLYAXON_AUTH_LDAP_REQUIRE_GROUP: {{ .Values.ldap.requireGroup | quote }}
  {{- end }}
  {{- if .Values.ldap.denyGroup }}
  POLYAXON_AUTH_LDAP_DENY_GROUP: {{ .Values.ldap.denyGroup | quote }}
  {{- end }}
  {{- end }}
