{{- if .Values.streams.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-streams
  labels:
{{ include "config.labels.apps.streams" . | indent 4 }}
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
  {{- with .Values.streams.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.streams.service.type }}
  selector:
{{ include "config.labels.apps.streams" . | indent 4 }}
  ports:
  - port: {{ .Values.streams.service.port }}
    targetPort: {{ .Values.streams.service.targetPort }}
    {{ if eq .Values.streams.service.type "NodePort" -}}
    nodePort: {{ .Values.streams.service.nodePort }}
    {{- end }}
    name: {{ .Values.streams.service.name }}
{{- end }}
