{{- if and .Values.streams.enabled .Values.streams.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "polyaxon.fullname" . }}-streams
  labels:
{{ include "config.labels.apps.streams" . | indent 4 }}
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "polyaxon.fullname" . }}-streams
  minReplicas: {{ .Values.streams.hpa.minpods }}
  maxReplicas: {{ .Values.streams.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.streams.hpa.cputhreshold }}
{{- end }}
