{{- if .Values.streams.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-streams
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 4 }}
  labels:
{{ include "config.labels.apps.streams" . | indent 4 }}
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
spec:
  replicas: {{ .Values.streams.replicas }}
  selector:
    matchLabels:
{{ include "config.labels.apps.streams" . | indent 6 }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 8 }}
      labels:
{{ include "config.labels.apps.streams" . | indent 8 }}
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreApi" . | indent 8 }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.agent.sa" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-streams
        image: "{{ .Values.streams.image }}:{{ .Values.streams.imageTag }}"
        imagePullPolicy: {{ .Values.streams.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.streams.service.targetPort }}
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.agent" . | indent 8 }}
{{ include "config.artifactsStore.envFrom" . | indent 8 }}
        env:
{{ include "config.debugMode" . | indent 8 }}
        volumeMounts:
{{ include "config.artifactsStore.mount" . | indent 8}}
        livenessProbe:
          httpGet:
            path: /healthz/
            port: {{ .Values.streams.service.targetPort }}
            scheme: {{ .Values.streams.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-streams
            {{- end }}
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz/
            port: {{ .Values.streams.service.targetPort }}
            scheme: {{ .Values.streams.service.scheme | default "HTTP" }}
            {{- if .Values.allowedHosts }}
            httpHeaders:
              - name: Host
                value: {{ template "polyaxon.fullname" . }}-streams
            {{- end }}
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 2
        resources:
          requests:
{{ toYaml .Values.streams.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.streams.resources.limits | indent 12 }}
          {{- end }}
      volumes:
{{ include "config.artifactsStore.volume" . | indent 6}}
{{- end }}
