apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  namespace: postgres-test
  labels:
    app: postgres-test
spec:
  type: LoadBalancer
  selector:
    app: postgres-test
  ports:
  - port: 5432
    name: postgres-test
