{{- if (not .Values.secret) }}
{{- if .Values.agent.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent-secret
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent-secret
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
type: Opaque
data:
  POLYAXON_AUTH_TOKEN: {{ .Values.agent.token | b64enc | quote }}
{{- end }}
{{- end }}
