{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-gateway
  labels:
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreApi" . | indent 4 }}
{{ include "config.labels.apps.gateway" . | indent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
{{ include "config.labels.apps.gateway" . | indent 4 }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: {{ .Values.gateway.service.targetPort }}
    {{ if eq .Values.gateway.service.type "NodePort" -}}
    nodePort: {{ .Values.gateway.service.nodePort }}
    {{- end }}
    name: {{ .Values.gateway.service.name }}
{{- end }}
