apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "polyaxon.fullname" . }}-runs-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-runs-sa
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "polyaxon.fullname" . }}-runs-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-runs-role
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes", "apis"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "*"]
    resources: ["events", "pods/status", "pods/log"]
    verbs: ["watch", "get", "list"]
  - apiGroups: ["core.polyaxon.com"]
    resources: ["operations"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "polyaxon.fullname" . }}-runs-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-runs-role-binding
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "polyaxon.fullname" . }}-runs-role
subjects:
  - kind: ServiceAccount
    name: {{ template "polyaxon.fullname" . }}-runs-sa
    namespace: {{ .Release.Namespace }}
