apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab
  namespace: spark
  labels:
    app: jupyterlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi