apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
  namespace: spark
spec:
  selector:
    matchLabels:
      app: jupyterlab
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      volumes:
        - name: jupyterlab
          persistentVolumeClaim:
            claimName: jupyterlab
      containers:
      - name: jupyterlab
        image: 10.152.183.174:5000/jupyterlab:3.1.2-hadoop-3.2.0-aws.v01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        env:
        - name: GRANT_SUDO
          value: "yes"
        command: ["/bin/sh", "-c"]
        args:
         - IPYTHONDIR=.ipython jupyter lab --debug --LabApp.token='' --allow-root --port=8888;
        volumeMounts:
          - mountPath: /home/notebook
            name: jupyterlab
