apiVersion: v1
kind: Service
metadata:
  name: jupyter-spark
  namespace: spark
  labels:
    app: jupyter-spark
spec:
  type: LoadBalancer
  selector:
    app: jupyter
  ports:
  - port: 8888
    name: jupyter
