apiVersion: apps/v1
kind: Deployment
metadata:
  name: elyra
  namespace: elyra
spec:
  selector:
    matchLabels:
      app: elyra
  replicas: 1
  template:
    metadata:
      labels:
        app: elyra
    spec:
      volumes:
        - name: elyra
          persistentVolumeClaim:
            claimName: elyra
      containers:
      - name: elyra
        image: elyra/elyra:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: elyra
          protocol: TCP
        env:
        - name: JUPYTERLAB_S3_ENDPOINT
          value: "http://10.152.183.240:9000"
        - name: JUPYTERLAB_S3_ACCESS_KEY_ID
          value: "access-key"
        - name: JUPYTERLAB_S3_SECRET_ACCESS_KEY
          value: "secret-key"
        - name: AWS_ACCESS_KEY_ID
          value: "access-key"
        - name: AWS_SECRET_ACCESS_KEY
          value: "secret-key"
        - name: GRANT_SUDO
          value: "yes"
        command: ["/bin/sh", "-c"]
        args:
         - conda install -c conda-forge nodejs;
           conda install -c conda-forge mamba_gator;
           pip install --upgrade pip;
           pip install nodejs;
           pip install ipympl;
           pip install jupyterlab_s3_browser;
           pip install jupyterlab-tabular-data-editor;
           pip install jupyterlab-plugin-graph;
           pip install jupyterlab-spreadsheet-editor;
           pip install jupyter-dash;
           pip install jlab-enhanced-cell-toolbar;
           pip install lckr-jupyterlab-variableinspector;
           jupyter serverextension enable --py jupyterlab_s3_browser;
           jupyter labextension install jupyterlab-chart-editor;
           jupyter labextension build;
           jupyter lab --debug --LabApp.token='';
        volumeMounts:
          - mountPath: /home/jovyan/work
            name: elyra
