apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-admin-user"
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-admin-user
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHooks" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-admin-user"
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-admin-user
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.imagePullSecrets" . | indent 6}}
      restartPolicy: Never
      activeDeadlineSeconds: 360
      containers:
      - name: admin-user-job
        image: "{{ template "config.apiHooks.image" . }}:{{ template "config.apiHooks.imageTag" . }}"
        imagePullPolicy: {{ template "config.apiHooks.imagePullPolicy" . }}
        args: ["createuser", "--username={{ .Values.user.username }}", "--email={{ .Values.user.email }}", "--password=$(POLYAXON_ADMIN_PASSWORD)", "--superuser", "--force"]
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.manageEnvs" . | indent 8 }}
