{{- if .Values.externalServices.postgresql.pgbouncer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-pgbouncer
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  labels:
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHelpers" . | indent 4 }}
{{ include "config.labels.apps.pgbouncer" . | indent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0  # Avoid Terminating and ContainerCreating at the same time
  selector:
    matchLabels:
{{ include "config.labels.apps.pgbouncer" . | indent 6 }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      labels:
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreHelpers" . | indent 8 }}
{{ include "config.labels.apps.pgbouncer" . | indent 8 }}
    spec:
{{ include "config.scheduling" . | indent 6 }}
      containers:
        - name: {{ .Chart.Name }}-pgbouncer
          image: "{{ .Values.externalServices.postgresql.pgbouncer.image }}:{{ .Values.externalServices.postgresql.pgbouncer.imageTag }}"
          imagePullPolicy: {{ .Values.externalServices.postgresql.pgbouncer.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ template "pgsql.port" . }}
          env:
            - name: POOL_MODE
              value: session
            - name: SERVER_RESET_QUERY
              value: DISCARD ALL
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_PORT
              value: "5433"
            - name: DB_USER
              value: "{{ template "pgsql.user" . }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.platformSecret }}
                  name: {{ .Values.platformSecret }}
                  key: POLYAXON_DB_PASSWORD
                {{- else }}
                  name: {{ template "polyaxon.fullname" . }}-postgresql-secret
                  key: postgresql-password
                {{- end }}
            - name: MAX_CLIENT_CONN
              value: {{ .Values.externalServices.postgresql.pgbouncer.maxClientConn | default "500" | quote }}
            - name: DEFAULT_POOL_SIZE
              value: {{ .Values.externalServices.postgresql.pgbouncer.defaultPoolSize | default "50" | quote }}
          readinessProbe:
            tcpSocket:
              port: {{ template "pgsql.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: {{ template "pgsql.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                # Allow existing queries clients to complete within 120 seconds
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['all']
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 800Mi
        - name: cloudsql-proxy
          image: "{{ .Values.externalServices.postgresql.pgbouncer.proxyImage }}:{{ .Values.externalServices.postgresql.pgbouncer.proxyImageTag }}"
          imagePullPolicy: {{ .Values.externalServices.postgresql.pgbouncer.proxyImagePullPolicy | default "IfNotPresent" }}
          command:
            [
              '/cloud_sql_proxy',
              '--dir=/cloudsql',
              '-instances={{ .Values.externalServices.postgresql.host }}',
              '-credential_file=/secrets/cloudsql/credentials.json',
            ]
          volumeMounts:
            - name: cloudsql-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-credentials
          secret:
            secretName: cloudsql-credentials
        - name: cloudsql
          ? emptyDir
{{- end }}
