apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
    release: docker-registry-ui
    app/version: "2.0.0"
  name: docker-registry
  namespace: docker-registry
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 20Gi
