apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: docker-registry
  labels:
    app: registry
    release: docker-registry-ui
    app/version: "2.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: registry
      protocol: TCP
      name: registry
  selector:
      app: registry
      release: docker-registry-ui
