apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-ui
  namespace: docker-registry
  labels:
    app: registry-ui
    release: docker-registry-ui
    app/version: "2.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
      release: docker-registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
        release: docker-registry-ui
    spec:
      containers:
        - name: registry-ui
          image: "docker.io/joxit/docker-registry-ui:latest"
          imagePullPolicy: Always
          env:
            - name: REGISTRY_TITLE
              value: "Docker registry UI"
            - name: DELETE_IMAGES
              value: "false"
            - name: NGINX_PROXY_PASS_URL
              value: "http://10.152.183.174:5000"
            - name: PULL_URL
              value: "10.152.183.174:5000"
            - name: SINGLE_REGISTRY
              value: "true"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}

