apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-datagen
  name: ksql-datagen
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksql-datagen
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-datagen
    spec:
      containers:
        - args:
            - bash
            - -c
            - echo Waiting for Kafka to be ready... && cub kafka-ready -b broker:29092 1 40 && echo Waiting for Confluent Schema Registry to be ready... && cub sr-ready schema-registry 8081 40 && echo Waiting a few seconds for topic creation to finish... && sleep 11 && tail -f /dev/null
          env:
            - name: KSQL_CONFIG_DIR
              value: /etc/ksql
            - name: STREAMS_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: STREAMS_SCHEMA_REGISTRY_HOST
              value: schema-registry
            - name: STREAMS_SCHEMA_REGISTRY_PORT
              value: "8081"
          image: confluentinc/ksqldb-examples:6.2.0
          name: ksql-datagen
          resources: {}
      hostname: ksql-datagen
      restartPolicy: Always
status: {}
