{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-flower
  labels:
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHelpers" . | indent 4 }}
{{ include "config.labels.apps.flower" . | indent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  selector:
{{ include "config.labels.apps.flower" . | indent 4 }}
  ports:
  - port: {{ .Values.flower.service.port }}
    targetPort: {{ .Values.flower.service.targetPort }}
    {{ if eq .Values.flower.service.type "NodePort" -}}
    nodePort: {{ .Values.flower.service.nodePort }}
    {{- end }}
    name: {{ .Values.flower.service.name }}
{{- end }}
