{{- if .Values.externalServices.postgresql.pgbouncer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "polyaxon.fullname" . }}-pgbouncer
  labels:
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHelpers" . | indent 4 }}
{{ include "config.labels.apps.pgbouncer" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ template "pgsql.port" . }}
    targetPort: {{ template "pgsql.port" . }}
    protocol: TCP
    name: postgres
  selector:
{{ include "config.labels.apps.pgbouncer" . | indent 4 }}
{{- end }}
