dependencies:
  - name: postgresql
    version: 8.2.1
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
  - name: rabbitmq-ha
    version: 1.34.0
    repository: https://charts.helm.sh/stable
    condition: rabbitmq-ha.enabled
  - name: redis
    version: 10.7.16
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
