spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  template:
    metadata:
      labels:
        name: nginx-ingress-microk8s
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: nginx-ingress-microk8s-serviceaccount
      containers:
      - image: k8s.gcr.io/ingress-nginx/controller:v1.0.0-alpha.2@sha256:04a0ad3a1279c2a58898e789eed767eafa138ee1e5b9b23a988c6e8485cf958d
        name: nginx-ingress-microk8s