apiVersion: v1
kind: Service
metadata:
  name: tb-kafka-svc
  namespace: thingsboard
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-int
  selector:
    app: tb-kafka