oom_score = 0
version = 2

[cgroup]
  path = ""

[debug]
  address = ""
  gid = 0
  uid = 0

[grpc]
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216
  uid = 0

[metrics]
  address = "127.0.0.1:1338"
  grpc_histogram = false

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]
    enable_selinux = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    sandbox_image = "k8s.gcr.io/pause:3.1"
    stats_collect_period = 10
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"

    [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "${SNAP_DATA}/opt/cni/bin"
      conf_dir = "${SNAP_DATA}/args/cni-network"

    [plugins."io.containerd.grpc.v1.cri".containerd]
      no_pivot = false
      snapshotter = "${SNAPSHOTTER}"

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
            BinaryName = "kata-runtime"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia-container-runtime]
          runtime_type = "io.containerd.runc.v1"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia-container-runtime.options]
            BinaryName = "nvidia-container-runtime"

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v1"

    [plugins."io.containerd.grpc.v1.cri".registry]

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]

        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]

        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:32000"]
          endpoint = ["http://localhost:32000"]