apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-test
  namespace: postgres-test
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi